# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
    paths-ignore:
      - bundle
      - README.md

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Packing up files
        run: |
          mkdir -p bundle
          ls *.pde | xargs cat *.pde > bundle.pde
          mv bundle.pde bundle

      # Form a commit
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Processing-Stubs CI"
          set +e
          git add -A
          git commit -m "Automated build"
          set -e

      # Push that file back up
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
